# Generated by Django 4.2.13 on 2024-06-08 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_remove_job_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="due",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
