databases:
  - name: sebastian_render_db
    databaseName: sebastian_render_db
    user: sebastian_admin
    region: oregon
    plan: free

services:
  - type: web
    name: sebastian
    env: python
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn sebastian.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sebastian_render_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

    autoDeploy: true