# Generated by Django 4.2.13 on 2024-06-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_shift_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="worker_credit",
            field=models.IntegerField(default=0, verbose_name="worker_credit"),
        ),
    ]
