# Generated by Django 4.2.13 on 2024-06-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_worker_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shift_assigned",
            field=models.IntegerField(default=0, verbose_name="shift_assigned"),
        ),
    ]
