# Generated by Django 4.2.13 on 2024-05-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("IN_PROGRESS", "In Progress"),
                    ("EVALUATION", "Under Evaluation"),
                    ("COMPLETED", "Completed"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
