# Generated by Django 4.2.13 on 2024-06-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
