# Generated by Django 4.2.13 on 2024-06-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_job_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="approved",
        ),
    ]
