# Generated by Django 4.2.13 on 2024-05-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("contact_address", models.CharField(max_length=255)),
                ("task_completed", models.BooleanField(default=False)),
                ("task_assigned", models.BooleanField(default=False)),
                ("due", models.DateField()),
            ],
        ),
    ]
