# Generated by Django 4.2.13 on 2024-06-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="due",
            field=models.DateField(blank=True, null=True),
        ),
    ]
