# Generated by Django 4.2.13 on 2024-06-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_due"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="due",
            field=models.DateField(),
        ),
    ]
