# Generated by Django 4.2.13 on 2024-06-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_shift_assigned"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shift_assigned_done",
            field=models.IntegerField(default=0, verbose_name="shift_assigned_done"),
        ),
    ]
